# @format

name: hozzo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3+27

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # state management
  stacked: ^1.7.6
  stacked_hooks: ^0.1.3+1
  # navigation
  auto_route:
  stacked_services:
  # inversion of control
  get_it:
  injectable:
  flutter_hooks: ^0.14.1
  graphql_flutter: ^3.1.0
  shared_preferences: ^0.5.12
  flutter_svg: ^0.19.0

  pull_to_refresh: ^1.6.2
  url_launcher: ^5.7.2
  launch_review: ^2.0.0
  share: ^0.6.5+2
  smooth_page_indicator: ^0.2.0
  cached_network_image: ^2.4.1
  shimmer: ^1.1.1
  modal_bottom_sheet: ^0.2.2
  pinput: ^0.2.6
  email_validator: ^1.0.6
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  dropdown_search: ^0.4.8
  flutter_typeahead: ^1.8.8
  flutter_swiper: ^1.1.6
  flutter_switch: ^0.1.4
  date_picker_timeline: ^1.2.1
  date_util: ^0.1.4
  appbar_elevation: ^0.1.0
  dotted_decoration: ^1.2.2
  flutter_custom_clippers: ^1.1.2
  timeline_tile: ^1.0.0
  image_picker: ^0.6.7+14
  flutter_rating_bar: ^3.2.0
  google_maps_flutter: ^1.0.6
  google_place: ^0.3.3
  geolocator: ^6.1.8+1
  razorpay_flutter: ^1.2.5
  image_cropper: ^1.3.1
  package_info: ^0.4.3+4
  firebase_core: "^0.7.0"
  firebase_messaging: "^8.0.0-dev.15"
  expandable_page_view: ^1.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "FFFFFF"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    # Mocks Folders
    - assets/mocks/
    - assets/mocks/vehicle_types/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Regular.ttf
        - asset: fonts/Gotham-Light.ttf
          weight: 300
        - asset: fonts/Gotham-Medium.ttf
          weight: 500
        # - asset: fonts/Gotham-SemiBold.ttf
        #   weight: 600
        - asset: fonts/Gotham-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
